name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'  # Cambiado de 'npm' a 'yarn'
    - name: Install dependencies with Yarn
      run: yarn install  # Cambiado de npm a Yarn
    - name: Build
      run: yarn run build --if-present  # Ajustado para usar Yarn
    #- name: Test
     # run: yarn test  # Ajustado para usar Yarn
